version: "3"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
      - "5001:5001"
    networks: 
      - "justTradeIt"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - RABBITMQ_DEFAULT_USER=justTradeIt
      - RABBITMQ_DEFAULT_PASS=justTradeIt
      - RABBITMQ_DEFAULT_HOST="notification-service"
    networks:
      - "justTradeIt"
    depends_on:
      - message-broker
      
  message-broker:
    image: rabbitmq:3.8
    container_name: message-broker
    environment:
      - RABBITMQ_DEFAULT_USER=justTradeIt
      - RABBITMQ_DEFAULT_PASS=justTradeIt
      - RABBITMQ_DEFAULT_HOST=localhost
    networks:
      - "justTradeIt"

networks:
  justTradeIt:
    driver: bridge
        